# unbound-dns - an Ansible playbook to configure Unbound for PiHole
# Copyright (C) 2023  Charles German <5donuts@pm.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure Unbound for PiHole
  hosts: pihole
  become: true

  pre_tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure dependencies are installed and up-to-date
      ansible.builtin.apt:
        state: latest
        name:
          - unbound
          - dnsutils # for dig

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Write Unbound configuration files
      ansible.builtin.import_tasks: tasks/config.yml

    # See: https://docs.pi-hole.net/guides/dns/unbound/#disable-resolvconfconf-entry-for-unbound-required-for-debian-bullseye-releases
    - name: Disable resolvconf.conf entry for Unbound
      ansible.builtin.import_tasks: tasks/bullseye.yml
      when:
        - ansible_facts.os_family == "Debian"
        - ansible_facts.distribution_version >= 11
