# unbound-dns - an Ansible playbook to configure Unbound for PiHole
# Copyright (C) 2023  Charles German <5donuts@pm.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: Write /etc/unbound/unbound.conf.d/pi-hole.conf
  ansible.builtin.template:
    src: templates/pi-hole.conf.j2
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    mode: "0644" # rw-r--r--
  notify:
    - Restart Unbound
    - Ensure DNS resolution of pi-hole.net is successful
    - Ensure DNSSEC validation returns SERVFAIL when expected
    - Ensure DNSSEC validation returns NOERROR and an IP address when expected

- name: Reduce FTL (PiHole) EDNS reassembly buffer size
  become: yes
  ansible.builtin.template:
    src: templates/99-edns.conf.j2
    dest: /etc/dnsmasq.d/99-edns.conf
    mode: "0644" # rw-r--r--
